export { default as LandingPage } from './landing_page/LandingPage'
export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as Account } from './account/Account'
export { default as NotFound } from './404-Page/NotFound'
